version: '3.8'

services:
  # PostgreSQL with PGVector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: tldr-postgres
    environment:
      POSTGRES_DB: tldr_dev
      POSTGRES_USER: tldr_user
      POSTGRES_PASSWORD: tldr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tldr_user -d tldr_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  # OpenSearch for local development (advanced search features)
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: tldr-opensearch
    environment:
      - cluster.name=tldr-cluster
      - node.name=tldr-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9201:9200"
      - "9601:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # OpenSearch Dashboards (optional - for development debugging)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: tldr-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch

volumes:
  postgres_data:
  opensearch_data: